name: assets_repository
description: Dart package which manages the assets handling.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  supabase_flutter: ^1.10.22
  equatable: ^2.0.5
  user_repository:
    path: ../user_repository
